In [2]:
import os
import cv2
import numpy as np
import matplotlib.pyplot as plt

In [9]:
# process first data set that contains three labels
data_path = '../data/first dataset'
labels = os.listdir(data_path)
print(labels)

['Correct', 'Incorrect', 'NoMask']


In [10]:
# assign corresponding number with character label help to predict
labels_num = [i for i in range(len(labels))]
label_dict = dict(zip(labels, labels_num))
print(labels)
print(label_dict)

['Correct', 'Incorrect', 'NoMask']
{'Correct': 0, 'Incorrect': 1, 'NoMask': 2}


In [15]:
# fixed image size to reduce feature size
img_size = 100
raw_image_data = [] # raw pixel representation
feature_data = [] # color histogram representation
label = []

In [17]:
for l in labels:
    fpath = os.path.join(data_path, l)
    img_lists=os.listdir(fpath)
    
    # fetch each image
    for img_name in img_lists:
        ipath = os.path.join(fpath, img_name)
        img = cv2.imread(ipath)
        
        # allow us to use img in Pillow and resize it to low resolution with three channels
        img_raw=cv2.cvtColor(img, cv2.COLOR_BGR2RGB)
        resized_img = cv2.resize(img_raw, (img_size, img_size)).flatten()
        
        # feature matrix (3D histogram)
        hsv = cv2.cvtColor(img, cv2.COLOR_BGR2HSV)
        hist = cv2.calcHist([hsv], [0,1,2], None, [8,8,8], [0, 256, 0, 256, 0, 256])
        hist = cv2.normalize(hist, hist).flatten()
        
        # add data and label
        raw_image_data.append(resized_img)
        feature_data.append(hist)
        label.append(label_dict[l])

In [36]:
print(len(raw_image_data[0]))
print(len(feature_data[0]))
print(len(label))

30000
512
4559


In [37]:
raw_images = np.array(raw_image_data)
features = np.array(feature_data)
list_label = np.array(label)

In [39]:
print(raw_images.shape)
print(list_label.shape)

(4559, 30000)
(4559,)


In [31]:
np.savetxt('raw_images.csv', raw_images, delimiter=',')

In [28]:
print(raw_images)

[[ 73  59  46 ... 122 110  80]
 [135  75  55 ... 149  71  55]
 [ 39  35  30 ...  17  17  18]
 ...
 [ 88  84  90 ...   2   1   6]
 [ 61  64  83 ... 187 183 200]
 [ 55  44  42 ... 167 179 191]]


In [33]:
test = np.loadtxt('raw_images.csv', delimiter=',')

In [35]:
np.savetxt('features.csv', features, delimiter=',')
np.savetxt('labels.csv', list_label, delimiter=',')